//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistreFoncier.Resources.Home {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RegistreFoncier.Resources.Home.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bureaux du registre foncier.
        /// </summary>
        public static string Bureaux {
            get {
                return ResourceManager.GetString("Bureaux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nous avons six bureaux du registre foncier à Loèche, à Brigue, à Sierre, à Sion, à Martigny et à Monthey..
        /// </summary>
        public static string BureauxTexte {
            get {
                return ResourceManager.GetString("BureauxTexte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Centrale valaisanne des testaments.
        /// </summary>
        public static string Centrale {
            get {
                return ResourceManager.GetString("Centrale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les testaments sont annoncés à la centrale des testaments par le biais des notaires valaisans uniquement..
        /// </summary>
        public static string CentraleTexte {
            get {
                return ResourceManager.GetString("CentraleTexte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Consultation du registre foncier.
        /// </summary>
        public static string Consultation {
            get {
                return ResourceManager.GetString("Consultation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le registre foncier donne l&apos;état des droits sur les immeubles. Sont immatriculés comme immeubles au registre foncier : les biens-fonds, les droits distincts et permanents immatriculés au registre foncier, les mines et les parts de copropriété d&apos;un immeuble..
        /// </summary>
        public static string ConsultationTexte {
            get {
                return ResourceManager.GetString("ConsultationTexte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Consulter.
        /// </summary>
        public static string Consulter {
            get {
                return ResourceManager.GetString("Consulter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Plus de détails.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FAQ.
        /// </summary>
        public static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous pourrez trouver les réponses aux questions les plus fréquemment posées..
        /// </summary>
        public static string FAQTexte {
            get {
                return ResourceManager.GetString("FAQTexte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retour au sommet.
        /// </summary>
        public static string Retour {
            get {
                return ResourceManager.GetString("Retour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Registre Foncier 2020.
        /// </summary>
        public static string RF2020 {
            get {
                return ResourceManager.GetString("RF2020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le projet RF2020 a pour but de moderniser le registre foncier, d&apos;introduire le Registre foncier fédéral informatisé et de mettre en place un système d&apos;information sur les immeubles..
        /// </summary>
        public static string RF2020Texte {
            get {
                return ResourceManager.GetString("RF2020Texte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à En savoir plus.
        /// </summary>
        public static string Savoir {
            get {
                return ResourceManager.GetString("Savoir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service du registre foncier.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le Registre foncier est un service public chargé de donner l&apos;état des droits en relation avec les immeubles (par ex. les servitudes et les gages immobiliers) ainsi que de sécuriser les droits liés à la propriété foncière..
        /// </summary>
        public static string ServiceTexte {
            get {
                return ResourceManager.GetString("ServiceTexte", resourceCulture);
            }
        }
    }
}
