//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistreFoncier.Resources.Consultation {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Intercapi {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Intercapi() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RegistreFoncier.Resources.Consultation.Intercapi", typeof(Intercapi).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Demande d&apos;abonnement?.
        /// </summary>
        public static string Demande {
            get {
                return ResourceManager.GetString("Demande", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de passe oublié ?.
        /// </summary>
        public static string MDP {
            get {
                return ResourceManager.GetString("MDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Problèmes d&apos;accès ?.
        /// </summary>
        public static string Problèmes {
            get {
                return ResourceManager.GetString("Problèmes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retour au sommet.
        /// </summary>
        public static string Retour {
            get {
                return ResourceManager.GetString("Retour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les données du registre foncier sont désormais disponibles en ligne, via le système d’information Intercapi. Elles peuvent être consultées par les personnes disposant d’un droit d’accès. Les accès sont actuellement ouverts aux notaires, géomètres, teneurs de cadastres et administrations. &amp;nbsp;Nous travaillons à étendre ceux-ci aux personnes privées et autres ayant droits au sens de l’annexe 1 de l’Ordonnance cantonale sur le registre foncier informatisé..
        /// </summary>
        public static string Texte1 {
            get {
                return ResourceManager.GetString("Texte1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les utilisateurs précités disposent d’un accès aux données publiques du registre foncier. Ces données comprennent la désignation de l’immeuble, son descriptif, le nom et l’identification du propriétaire, la forme de la propriété ainsi que la date d’acquisition (art. 26 al. 1 ORF, art. 970 al. 2 CC)..
        /// </summary>
        public static string Texte2 {
            get {
                return ResourceManager.GetString("Texte2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Si vous ne disposez pas d’un accès à notre plateforme, ces informations ouvertes au public peuvent être obtenues auprès de nos bureaux de registres fonciers..
        /// </summary>
        public static string Texte3Gras {
            get {
                return ResourceManager.GetString("Texte3Gras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Si les conditions des art. 28 ss ORF et leurs dispositions d’exécution (Ordonnance cantonale sur la tenue du registre foncier informatisé) sont remplies, un accès étendu (droits de gages, servitudes…) peut être obtenu. Ce type d’accès est soumis à émoluments..
        /// </summary>
        public static string Texte4 {
            get {
                return ResourceManager.GetString("Texte4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pour l’obtention d’un accès public ou étendu, une demande fondée doit être déposée en vue de l’établissement d’une convention entre l’utilisateur et le canton. Pour ce faire, merci de retourner le formulaire à l&apos;adresse indiquée ci-contre..
        /// </summary>
        public static string Texte5 {
            get {
                return ResourceManager.GetString("Texte5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Consultation en ligne du registre.
        /// </summary>
        public static string Titre {
            get {
                return ResourceManager.GetString("Titre", resourceCulture);
            }
        }
    }
}
